Tries to find movie in local db, if not existing tries to find in ext…
munHunger/cosmos pull request #26
Opened 2017-10-23 20:12 UTC by rikardeliasson

…ernal source.

2017-10-23 20:20 UTC, munHunger requested changes

2017-10-23 20:20 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/business/Movies.java
> +    public Response getMovie(@ApiParam(value = "The query to search for") @PathParam("query") String query) throws Exception {
Skulle föredra att ha dessa som en query parameter

2017-10-23 20:20 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/business/Movies.java
> +            @ApiResponse(code = HttpServletResponse.SC_OK, message = "")})
Borde lägga till att den returnerar ett Movie response objekt

2017-10-23 20:20 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +            result = Database.getObjects("from Movie WHERE movie.title = :title", param);
Det här är case sensitive. kan vi det case insensitive?

2017-10-23 20:20 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +            String apiKey = Settings.getSettingsValue("movies.movie_db_api_key").get();
Kanske ska returnera ett fel om dessa inte hittas

2017-10-23 20:20 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +            final Client client = ClientBuilder.newClient();
Varför är denna final?

2017-10-23 20:20 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +                if (res.getStatus() != HttpServletResponse.SC_OK) throw new APIException(
Det här kommer slänga ett väldigt fult exception. borde istället returnera en 500 respons med ett ErrorMessage

2017-10-23 20:20 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +        return Response.ok(result.get(0)).build();
Kommer väldigt sannolikt slänga ArrayIndexOutOfBoundsException om man väl kommer hit.
Kommer man hit så har man väl inte hittat något, så kanske en 404?

2017-10-23 20:20 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +                return Response.ok(resulting).build();
Returnera en hel lista?

2017-10-23 20:51 UTC, rikardeliasson commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +            result = Database.getObjects("from Movie WHERE movie.title = :title", param);
testade och verkar inte vara case sensitive. Testfall American Assassin vs american assassin

2017-10-23 21:03 UTC, rikardeliasson commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +            final Client client = ClientBuilder.newClient();
ingen tanke alls från min sida. Den  i getRecommendations är final :) #lameanswer
jag hade satt den som inget alls om jag valt själv
har tagit bort final och det funkar fint

2017-10-23 21:14 UTC, rikardeliasson commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +                return Response.ok(resulting).build();
hell yeah! Vad tänkte du? Får sällan/aldrig bara en träff

2017-10-23 21:15 UTC, rikardeliasson commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +        return Response.ok(result.get(0)).build();
kommer man hit så har man hittat filmen/erna i databasen och returnerar den/dem

2017-10-24 04:46 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +        return Response.ok(result.get(0)).build();
Jag läste fel, my bad

2017-10-24 04:46 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +                return Response.ok(resulting).build();
Alltså det är väl fine, men det är inte konsekvent.
Hittar du något i lokal db så får du ju ingen lista tillbaka

2017-10-24 04:49 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +        return Response.ok(result.get(0)).build();
jag läste fel, my bad

2017-10-24 07:39 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +            } finally {
Om detta slänger en exception så får du en ArrayIndexOutOfBounds utåt

2017-10-24 13:10 UTC, munHunger requested changes

2017-10-24 13:10 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/business/Movies.java
> +    @Path("/search/{query}")
Den här Pathen är konstig då den inte tar in en path param.
Borde väl ändras till "/search" och låta query vara kvar som queryparam

2017-10-24 13:41 UTC, munHunger approved these changes

2017-10-24 13:41 UTC, merged