Cosmos 26
munHunger/cosmos pull request #29
Opened 2017-11-06 13:19 UTC by rikardeliasson

A lot of cleaning and refactoring

2017-11-07 07:48 UTC, munHunger requested changes

2017-11-07 07:48 UTC, munHunger commented on common/src/main/java/se/mulander/cosmos/common/model/movies/movie/MovieDaoImpl.java
>          return null;
Returnera Optional istället för eventuella nulls

2017-11-07 07:48 UTC, munHunger commented on common/src/main/java/se/mulander/cosmos/common/model/movies/movie/MovieDaoImpl.java
> +            e.printStackTrace();
Fixa exception hantering. alltså är inte upp exceptions utan släng något "generiskt"

2017-11-07 07:48 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +    private static Response presenceCheck(Optional<String> theMovieDbURL, Optional<String> apiKey) {
Vill gärna ha den här funktionen dokumenterad

2017-11-07 07:48 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +     * @param query the query filtering results, in current solution filters on title
Redundant att säga att den sorterar på titel i nuvarande lösning.
Räcker med att säga att den sorterar på titel

2017-11-07 07:48 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +        if (movie == null) {
byts ut mot Optional

2017-11-07 07:48 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +        return Response.ok(result.get(0)).build();
ser mongo ut

2017-11-09 12:01 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +        return movie;
Är detta tänkt som en builder-design?

2017-11-09 14:05 UTC, rikardeliasson commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +        return movie;
fanns ingen tanke med det nej?

2017-11-09 14:12 UTC, rikardeliasson commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +        return movie;
ville bara ha en clearextended även för enskilda movie objects

2017-11-09 15:13 UTC, munHunger commented on movies/src/main/java/se/mulander/cosmos/movies/impl/Movies.java
> +        return movie;
Tänkte mest på varför den returnerar mobile när det ändå är en sidoeffekt

2019-11-25 14:54 UTC, closed without merging